${license}
/**
This file was automatically generated by the OWL API Generator.
*/

package ${package};

import org.semanticweb.owlapi.model.OWLNamedIndividual;

import de.jpdigital.owlapisimplex.Instances;

import java.util.stream.Collectors;

/**
 * Repository class for the OWL class ${classIri}.
 **/
public class ${className} {

    private final Instances instances;

    public ${className}(final Instances instances) {
        this.instances = instances;
    }
    
    public Stream<OWLIndividuals> instances() {
        return instances.instances(${classIri});
    }

    public List<OWLIndividuals> getInstances() {
        return instances.getInstances(${classIri});
    }

    <#list dataProperties as dataProperty>

    public Stream<OWLNamedIndividual> instancesFilteredBy${dataProperty}(
        final String value
    ) {
        final String query = String.format(
            "${owlClassName} and (${dataProperty} value %s or ${dataProperty} value \"%s\")",
            value
        );
        return instances.instances(query);
    }

    public List<OWLNamedIndividual> getInstancesFilteredBy${dataProperty}(
        final String value
    ) {
        return instancesFilteredBy${dataProperty}(value)
            .collect(Collectors.toList());
    }

    </#list>

}
